#ifndef GODBLESSENGINE_GLOBAL_H
#define GODBLESSENGINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GODBLESSENGINE_LIBRARY)
#  define GODBLESSENGINE_EXPORT Q_DECL_EXPORT
#else
#  define GODBLESSENGINE_EXPORT Q_DECL_IMPORT
#endif

#endif // GODBLESSENGINE_GLOBAL_H
